import Foundation
import XCTest
import OKVideoCore
@testable import OKVideoPersistence

final class ImportedChannelRegistryTests: XCTestCase {
    private let source = LiveSourceID.imported(UUID(uuidString: "AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA")!)
    private let other = LiveSourceID.imported(UUID(uuidString: "BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB")!)
    private let date = Date(timeIntervalSince1970: 1_800_000_000.125)
    private let table = "imported_channel_identities"
    private func token(_ n: Int) -> UUID {
        UUID(uuidString: String(format: "00000000-0000-0000-0000-%012d", n))!
    }
    private func record(_ n: Int = 1, source: LiveSourceID? = nil, name: String = "频道", tvg: String? = nil,
                        upstream: String? = nil, lifecycle: ImportedChannelRegistryLifecycle = .active,
                        provenance: ImportedSourceProvenance = .verified,
                        updated: Date? = nil, created: Date? = nil, version: Int = 1, evidenceVersion: Int = 1) throws -> ImportedChannelRegistryRecord {
        ImportedChannelRegistryRecord(identity: try ImportedLiveChannelIdentity(source: source ?? self.source, localID: token(n)),
            evidence: ImportedChannelEvidence(group: "News", name: name,
                upstream: upstream.map { ImportedUpstreamEvidence(namespace: "fixture", value: $0, formatSupportsStableID: true) },
                tvgID: tvg), provenance: provenance, lifecycle: lifecycle,
            createdAt: created ?? date, updatedAt: updated ?? date, recordVersion: version, evidenceVersion: evidenceVersion)
    }
    private func url() throws -> URL {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent("OKVideoRegistryTests-\(UUID())")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        addTeardownBlock { try? FileManager.default.removeItem(at: directory) }
        return directory.appendingPathComponent("fixture.sqlite3")
    }
    private var fixtureURLs: [ObjectIdentifier: URL] = [:]
    private func store() throws -> SQLiteStore {
        let path = try url()
        let store = try SQLiteStore(databaseURL: path)
        fixtureURLs[ObjectIdentifier(store)] = path
        return store
    }
    private func fixtureURL(for store: SQLiteStore) -> URL { fixtureURLs[ObjectIdentifier(store)]! }
    private func expectRows(_ store: SQLiteStore, _ expected: [ImportedChannelRegistryRecord], source: LiveSourceID? = nil,
                            file: StaticString = #filePath, line: UInt = #line) async throws {
        let rows = try await store.importedChannelIdentities(for: source ?? self.source)
        XCTAssertEqual(rows, expected, file: file, line: line)
    }
    private func fails(_ expected: ImportedChannelRegistryError? = nil, file: StaticString = #filePath, line: UInt = #line,
                       _ operation: () async throws -> Void) async {
        do { try await operation(); XCTFail("Expected failure", file: file, line: line) }
        catch { if let expected { XCTAssertEqual(error as? ImportedChannelRegistryError, expected, file: file, line: line) } }
    }
    private func scalar(_ url: URL, _ sql: String) throws -> Int {
        let connection = try SQLiteConnection(url: url)
        defer { connection.close() }
        return try connection.scalarInt(sql)
    }
    private func execute(_ url: URL, _ sql: String, _ bindings: [SQLiteBinding] = []) throws {
        let connection = try SQLiteConnection(url: url)
        defer { connection.close() }
        try connection.execute(sql, bindings: bindings)
    }
    private func evidenceData(_ url: URL) throws -> Data {
        let connection = try SQLiteConnection(url: url)
        defer { connection.close() }
        var result: Data?
        try connection.query("SELECT evidence FROM \(table) ORDER BY local_id LIMIT 1") { result = connection.data($0, 0) }
        return try XCTUnwrap(result)
    }
    private func replaceEvidence(_ url: URL, _ data: Data) throws {
        try execute(url, "UPDATE \(table) SET evidence = ?", [.blob(data)])
    }
    /// Strip only the new schema in a temporary fixture. All older tables retain
    /// the real v9 layout/data generated by the unchanged v1...v9 migration chain.
    private func legacyURL() throws -> URL {
        let value = try url()
        do { _ = try SQLiteStore(databaseURL: value) }
        try execute(value, "DROP TABLE \(table)")
        try execute(value, "PRAGMA user_version = 9")
        return value
    }

    func testCleanDatabaseCreatesEmptyRegistry() async throws {
        let store = try store()
        try await expectRows(store, [])
        XCTAssertEqual(try scalar(fixtureURL(for: store), "PRAGMA user_version"), 10)
        XCTAssertEqual(try scalar(fixtureURL(for: store), "SELECT count(*) FROM sqlite_master WHERE type='table' AND name='\(table)'"), 1)
    }
    func testVersionNineMigrationAddsEmptyRegistry() async throws {
        let path = try legacyURL()
        let store = try SQLiteStore(databaseURL: path)
        try await expectRows(store, [])
        XCTAssertEqual(try scalar(path, "PRAGMA user_version"), 10)
    }
    func testMigrationReopenIsIdempotentAndRetainsRecords() async throws {
        let path = try legacyURL()
        let expected = try record()
        do {
            let store = try SQLiteStore(databaseURL: path)
            try await store.applyImportedChannelIdentityMutations([.upsert(expected)])
        }
        for _ in 0..<3 {
            let store = try SQLiteStore(databaseURL: path)
            try await expectRows(store, [expected])
            XCTAssertEqual(try scalar(path, "PRAGMA user_version"), 10)
        }
    }
    func testMigrationFailureRollsBackTableAndVersionThenRetries() async throws {
        let path = try legacyURL()
        try execute(path, "CREATE TABLE fault_fixture (value TEXT)")
        try execute(path, "INSERT INTO fault_fixture VALUES ('preserved')")
        // Fail CREATE INDEX after CREATE TABLE succeeded inside the migration.
        try execute(path, "CREATE INDEX imported_channel_identities_source_lifecycle ON fault_fixture(value)")
        XCTAssertThrowsError(try SQLiteStore.openRecovering(databaseURL: path))
        XCTAssertEqual(try scalar(path, "PRAGMA user_version"), 9)
        XCTAssertEqual(try scalar(path, "SELECT count(*) FROM sqlite_master WHERE name='\(table)'"), 0)
        XCTAssertEqual(try scalar(path, "SELECT count(*) FROM fault_fixture WHERE value='preserved'"), 1)
        let siblings = try FileManager.default.contentsOfDirectory(atPath: path.deletingLastPathComponent().path)
        XCTAssertFalse(siblings.contains { $0.hasPrefix("Corrupt-") })
        try execute(path, "DROP INDEX imported_channel_identities_source_lifecycle")
        let store = try SQLiteStore(databaseURL: path)
        try await expectRows(store, [])
        XCTAssertEqual(try scalar(path, "PRAGMA user_version"), 10)
    }
    func testInsertAndFetchRoundTrip() async throws {
        let store = try store(), expected = try record(tvg: "CCTV1", upstream: "stable")
        try await store.applyImportedChannelIdentityMutations([.upsert(expected)])
        let actual = try await store.importedChannelIdentity(expected.identity)
        XCTAssertEqual(actual, expected)
    }
    func testFetchMissingIsNil() async throws {
        let store = try store()
        let actual = try await store.importedChannelIdentity(record().identity)
        XCTAssertNil(actual)
    }
    func testListIsSourceScopedAndDeterministicallyOrdered() async throws {
        let store = try store(), a = try record(), b = try record(2), foreign = try record(source: other)
        try await store.applyImportedChannelIdentityMutations([.upsert(b), .upsert(foreign), .upsert(a)])
        try await expectRows(store, [a, b])
        try await expectRows(store, [foreign], source: other)
    }
    func testSameLocalUUIDInDifferentSourcesIsIsolated() async throws {
        let store = try store(), a = try record(), b = try record(source: other, name: "Other")
        try await store.applyImportedChannelIdentityMutations([.upsert(a), .upsert(b)])
        let actualA = try await store.importedChannelIdentity(a.identity)
        let actualB = try await store.importedChannelIdentity(b.identity)
        XCTAssertEqual(actualA, a)
        XCTAssertEqual(actualB, b)
        XCTAssertEqual(try scalar(fixtureURL(for: store), "SELECT count(*) FROM \(table)"), 2)
    }
    func testRepeatedUpsertIsIdempotent() async throws {
        let store = try store(), value = try record()
        for _ in 0..<3 { try await store.applyImportedChannelIdentityMutations([.upsert(value), .upsert(value)]) }
        try await expectRows(store, [value])
    }
    func testSQLPrimaryKeyEnforcesSourceAndLocalUniqueness() async throws {
        let store = try store(), value = try record()
        try await store.applyImportedChannelIdentityMutations([.upsert(value)])
        XCTAssertThrowsError(try execute(fixtureURL(for: store), "INSERT INTO \(table) SELECT * FROM \(table)"))
        try await expectRows(store, [value])
    }
    func testEvidenceUpdateKeepsIdentityAndCreatedAt() async throws {
        let store = try store(), original = try record()
        let updated = try record(name: "Renamed", tvg: "new", upstream: "now-present", updated: date.addingTimeInterval(30))
        try await store.applyImportedChannelIdentityMutations([.upsert(original)])
        try await store.applyImportedChannelIdentityMutations([.upsert(updated)])
        try await expectRows(store, [updated])
        XCTAssertEqual(updated.identity, original.identity)
        XCTAssertEqual(updated.createdAt, original.createdAt)
    }
    func testStaleUpdateAndChangedCreationTimeAreRejected() async throws {
        let store = try store(), newer = try record(updated: date.addingTimeInterval(30))
        try await store.applyImportedChannelIdentityMutations([.upsert(newer)])
        await fails(.staleUpdate) { try await store.applyImportedChannelIdentityMutations([.upsert(record())]) }
        await fails(.staleUpdate) {
            try await store.applyImportedChannelIdentityMutations([.upsert(record(updated: date.addingTimeInterval(60), created: date.addingTimeInterval(1)))])
        }
        try await expectRows(store, [newer])
    }
    func testTrueCloseAndReopenPersistence() async throws {
        let path = try url(), expected = try record()
        weak var weakStore: SQLiteStore?
        do {
            let store = try SQLiteStore(databaseURL: path)
            weakStore = store
            try await store.applyImportedChannelIdentityMutations([.upsert(expected)])
        }
        XCTAssertNil(weakStore)
        let reopened = try SQLiteStore(databaseURL: path)
        try await expectRows(reopened, [expected])
    }
    func testCoreEvidenceCodableAndDatabaseRoundTrip() async throws {
        let store = try store()
        let evidence = ImportedChannelEvidence(group: "频道组", name: "频道", upstream: ImportedUpstreamEvidence(
            namespace: "fixture", value: "01", formatSupportsStableID: false), tvgID: "EPG", region: "北京", language: "zh", channelType: "news")
        XCTAssertEqual(try JSONDecoder().decode(ImportedChannelEvidence.self, from: JSONEncoder().encode(evidence)), evidence)
        let value = ImportedChannelRegistryRecord(identity: try record().identity, evidence: evidence,
            provenance: .unknown, lifecycle: .unresolved, createdAt: date, updatedAt: date)
        try await store.applyImportedChannelIdentityMutations([.upsert(value)])
        try await expectRows(store, [value])
    }
    func testTimestampsAndVersionsRoundTrip() async throws {
        let store = try store(), value = try record(updated: date.addingTimeInterval(0.25))
        try await store.applyImportedChannelIdentityMutations([.upsert(value)])
        let fetched = try await store.importedChannelIdentity(value.identity)
        let actual = try XCTUnwrap(fetched)
        XCTAssertEqual(actual.recordVersion, 1)
        XCTAssertEqual(actual.evidenceVersion, 1)
        XCTAssertEqual(actual.createdAt, date)
        XCTAssertEqual(actual.updatedAt, value.updatedAt)
    }
    func testKnownOptionalFieldsMayBeMissing() async throws {
        let store = try store(), value = try record()
        try await store.applyImportedChannelIdentityMutations([.upsert(value)])
        try replaceEvidence(fixtureURL(for: store), Data(#"{"group":"News","name":"频道"}"#.utf8))
        try await expectRows(store, [value])
    }
    func testUnknownEvidenceFieldPreservedAndBlocksOverwrite() async throws {
        let store = try store(), value = try record()
        try await store.applyImportedChannelIdentityMutations([.upsert(value)])
        let bytes = Data(#"{"group":"News","name":"频道","futureOptional":true}"#.utf8)
        try replaceEvidence(fixtureURL(for: store), bytes)
        await fails(.unsupportedFields) { _ = try await store.importedChannelIdentity(value.identity) }
        await fails(.unsupportedFields) { try await store.applyImportedChannelIdentityMutations([.upsert(value)]) }
        XCTAssertEqual(try evidenceData(fixtureURL(for: store)), bytes)
    }
    func testUnknownNestedUpstreamFieldFailsClosed() async throws {
        let store = try store(), value = try record()
        try await store.applyImportedChannelIdentityMutations([.upsert(value)])
        let bytes = Data(#"{"group":"News","name":"频道","upstream":{"namespace":"test","value":"1","formatSupportsStableID":true,"future":1}}"#.utf8)
        try replaceEvidence(fixtureURL(for: store), bytes)
        await fails(.unsupportedFields) { _ = try await store.importedChannelIdentity(value.identity) }
        XCTAssertEqual(try evidenceData(fixtureURL(for: store)), bytes)
    }
    func testFutureRecordAndEvidenceVersionsCannotBeOverwritten() async throws {
        for column in ["record_version", "evidence_version"] {
            let store = try store(), value = try record()
            try await store.applyImportedChannelIdentityMutations([.upsert(value)])
            try execute(fixtureURL(for: store), "UPDATE \(table) SET \(column) = 99")
            await fails(.unsupportedVersion) { _ = try await store.importedChannelIdentity(value.identity) }
            await fails(.unsupportedVersion) { try await store.applyImportedChannelIdentityMutations([.upsert(value)]) }
            XCTAssertEqual(try scalar(fixtureURL(for: store), "SELECT \(column) FROM \(table)"), 99)
        }
    }
    func testUnsupportedVersionWritesFailBeforePersistence() async throws {
        let store = try store()
        await fails(.unsupportedVersion) { try await store.applyImportedChannelIdentityMutations([.upsert(record(version: 2))]) }
        await fails(.unsupportedVersion) { try await store.applyImportedChannelIdentityMutations([.upsert(record(evidenceVersion: 2))]) }
        try await expectRows(store, [])
    }
    func testBatchAllSuccessAndRepeat() async throws {
        let store = try store(), values = try (1...30).map { try record($0) }
        let batch = values.map(ImportedChannelRegistryMutation.upsert)
        try await store.applyImportedChannelIdentityMutations(batch)
        try await store.applyImportedChannelIdentityMutations(batch)
        try await expectRows(store, values)
    }
    func testMiddleValidationFailureRollsBackEarlierSQLAndRetryWorks() async throws {
        let store = try store(), a = try record(), b = try record(2)
        await fails(.unsupportedVersion) {
            try await store.applyImportedChannelIdentityMutations([.upsert(a), .upsert(record(2, version: 2)), .upsert(record(3))])
        }
        try await expectRows(store, [])
        try await store.applyImportedChannelIdentityMutations([.upsert(a), .upsert(b)])
        try await expectRows(store, [a, b])
    }
    func testRealSQLFailureRollsBackEntireBatch() async throws {
        let store = try store(), a = try record(), b = try record(2)
        try execute(fixtureURL(for: store), """
            CREATE TRIGGER fixture_reject BEFORE INSERT ON \(table)
            WHEN NEW.local_id = '\(b.identity.localID.uuidString.lowercased())'
            BEGIN SELECT RAISE(ABORT, 'fixture failure'); END
            """)
        await fails { try await store.applyImportedChannelIdentityMutations([.upsert(a), .upsert(b)]) }
        try await expectRows(store, [])
        try execute(fixtureURL(for: store), "DROP TRIGGER fixture_reject")
        try await store.applyImportedChannelIdentityMutations([.upsert(a), .upsert(b)])
        try await expectRows(store, [a, b])
    }
    func testMixedRemoveUpdateInsertRollsBackTogether() async throws {
        let store = try store(), a = try record(), b = try record(2)
        try await store.applyImportedChannelIdentityMutations([.upsert(a), .upsert(b)])
        await fails {
            try await store.applyImportedChannelIdentityMutations([.remove(a.identity), .upsert(record(2, name: "Updated")),
                .upsert(record(3)), .upsert(record(4, version: 99))])
        }
        try await expectRows(store, [a, b])
    }
    func testNilUpstreamAndTVGArePersisted() async throws {
        let store = try store(), value = try record()
        try await store.applyImportedChannelIdentityMutations([.upsert(value)])
        try await expectRows(store, [value])
    }
    func testDuplicateTVGAndUpstreamDoNotViolateIdentityConstraints() async throws {
        let store = try store(), a = try record(tvg: "shared", upstream: "duplicate"), b = try record(2, tvg: "shared", upstream: "duplicate")
        try await store.applyImportedChannelIdentityMutations([.upsert(a), .upsert(b)])
        try await expectRows(store, [a, b])
    }
    func testDuplicateNormalizedNamesRemainSeparateRecords() async throws {
        let store = try store(), a = try record(name: "News"), b = try record(2, name: "NEWS")
        try await store.applyImportedChannelIdentityMutations([.upsert(a), .upsert(b)])
        try await expectRows(store, [a, b])
    }
    func testLifecycleValuesAndScopedFilterRoundTrip() async throws {
        let store = try store()
        let states: [ImportedChannelRegistryLifecycle] = [.active, .missing, .unresolved, .retired]
        let values = try states.enumerated().map { try record($0.offset + 1, lifecycle: $0.element) }
        try await store.applyImportedChannelIdentityMutations(values.map(ImportedChannelRegistryMutation.upsert))
        for (state, expected) in zip(states, values) {
            let rows = try await store.importedChannelIdentities(for: source, lifecycle: state)
            XCTAssertEqual(rows, [expected])
        }
    }
    func testLifecycleChangeIsExplicitAndDoesNotReallocate() async throws {
        let store = try store(), original = try record(), updated = try record(lifecycle: .missing)
        try await store.applyImportedChannelIdentityMutations([.upsert(original)])
        try await store.applyImportedChannelIdentityMutations([.upsert(updated)])
        try await expectRows(store, [updated])
    }
    func testUnknownLifecycleAndProvenanceFailClosed() async throws {
        for column in ["lifecycle", "provenance"] {
            let store = try store(), value = try record()
            try await store.applyImportedChannelIdentityMutations([.upsert(value)])
            try execute(fixtureURL(for: store), "UPDATE \(table) SET \(column) = 'future'")
            await fails(.unsupportedFields) { _ = try await store.importedChannelIdentity(value.identity) }
            await fails(.unsupportedFields) { try await store.applyImportedChannelIdentityMutations([.upsert(value)]) }
        }
    }
    func testRemoveOneAndRemoveSourceAreScopedAndIdempotent() async throws {
        let store = try store(), a = try record(), b = try record(2), foreign = try record(source: other)
        try await store.applyImportedChannelIdentityMutations([.upsert(a), .upsert(b), .upsert(foreign), .remove(a.identity)])
        try await expectRows(store, [b])
        try await store.applyImportedChannelIdentityMutations([.remove(a.identity), .removeAll(source: source), .removeAll(source: source)])
        try await expectRows(store, [])
        try await expectRows(store, [foreign], source: other)
    }
    func testSourceDeletionDoesNotCascadeOrAllocateOnReadd() async throws {
        let store = try store(), value = try record()
        guard case .imported(let id) = source else { return XCTFail() }
        let live = StoredLiveSource(id: id, name: "Fixture", sourceKind: .pasted, rawData: Data("#EXTM3U".utf8))
        try await store.saveLiveSource(live)
        try await store.applyImportedChannelIdentityMutations([.upsert(value)])
        try await store.deleteLiveSource(id: id)
        try await expectRows(store, [value])
        let replacement = StoredLiveSource(name: "Fixture", sourceKind: .pasted, rawData: live.rawData)
        try await store.saveLiveSource(replacement)
        try await expectRows(store, [], source: .imported(replacement.id))
    }
    func testNativeSourceRejectedByListAndRemoveAll() async throws {
        let store = try store()
        await fails(.unsupportedSource) { _ = try await store.importedChannelIdentities(for: .xtream(token(1))) }
        await fails(.unsupportedSource) { try await store.applyImportedChannelIdentityMutations([.removeAll(source: .xtream(token(1)))]) }
    }
    func testRegistryEvidenceHasNoTransportFields() async throws {
        let store = try store(), value = try record(tvg: "public", upstream: "public")
        try await store.applyImportedChannelIdentityMutations([.upsert(value)])
        let data = try evidenceData(fixtureURL(for: store))
        let json = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
        XCTAssertEqual(Set(json.keys), ["group", "name", "tvgID", "upstream"])
        for forbidden in ["url", "headers", "Cookie", "Authorization", "rawData", "SECRET_TOKEN_DO_NOT_PERSIST"] {
            XCTAssertFalse(String(decoding: data, as: UTF8.self).contains(forbidden))
        }
    }
    func testMisroutedURLAndSecretHeadersRejectedWithoutDiskCanary() async throws {
        let store = try store(), canary = "SECRET_TOKEN_DO_NOT_PERSIST"
        for text in ["https://fixture.invalid/live?token=\(canary)", "Authorization: Bearer \(canary)",
                     "Cookie: session=\(canary)", "password=\(canary)", "Bearer \(canary)"] {
            await fails(.unsafeEvidence) { try await store.applyImportedChannelIdentityMutations([.upsert(record(name: text))]) }
        }
        try await expectRows(store, [])
        for suffix in ["", "-wal", "-shm"] {
            let path = fixtureURL(for: store).path + suffix
            if FileManager.default.fileExists(atPath: path) {
                XCTAssertNil(try Data(contentsOf: URL(fileURLWithPath: path)).range(of: Data(canary.utf8)))
            }
        }
    }
    func testDiagnosticRepresentationDoesNotEchoMetadataOrErrors() throws {
        let canary = "SECRET_TOKEN_DO_NOT_PERSIST"
        let value = try record(name: canary, tvg: canary, upstream: canary)
        XCTAssertFalse(String(describing: value).contains(canary))
        XCTAssertFalse(String(reflecting: value).contains(canary))
        XCTAssertFalse(String(reflecting: ImportedChannelRegistryMutation.upsert(value)).contains(canary))
        XCTAssertFalse(String(reflecting: ImportedChannelRegistryError.unsafeEvidence).contains(canary))
    }
    func testInvalidTimestampsAndOversizedMetadataAreRejected() async throws {
        let store = try store()
        await fails(.invalidTimestamp) { try await store.applyImportedChannelIdentityMutations([.upsert(record(updated: date.addingTimeInterval(-1)))]) }
        await fails(.invalidTimestamp) { try await store.applyImportedChannelIdentityMutations([.upsert(record(updated: Date(timeIntervalSince1970: .infinity)))]) }
        await fails(.unsafeEvidence) { try await store.applyImportedChannelIdentityMutations([.upsert(record(name: String(repeating: "a", count: 2049)))]) }
        try await expectRows(store, [])
    }
    func testMalformedEvidenceFailsClosedWithoutLoss() async throws {
        let store = try store(), value = try record()
        try await store.applyImportedChannelIdentityMutations([.upsert(value)])
        let bytes = Data("not json".utf8)
        try replaceEvidence(fixtureURL(for: store), bytes)
        await fails(.invalidRecord) { _ = try await store.importedChannelIdentity(value.identity) }
        await fails(.invalidRecord) { try await store.applyImportedChannelIdentityMutations([.upsert(value)]) }
        XCTAssertEqual(try evidenceData(fixtureURL(for: store)), bytes)
    }
    func testEncodedEvidenceLimitAppliesBeforeWrite() async throws {
        let store = try store()
        let quoted = String(repeating: "\"", count: 2048)
        let evidence = ImportedChannelEvidence(group: quoted, name: quoted,
            upstream: ImportedUpstreamEvidence(namespace: quoted, value: quoted, formatSupportsStableID: true),
            tvgID: quoted, region: quoted, language: quoted, channelType: quoted)
        let value = ImportedChannelRegistryRecord(identity: try record().identity, evidence: evidence,
            provenance: .verified, lifecycle: .active, createdAt: date, updatedAt: date)
        await fails(.invalidRecord) { try await store.applyImportedChannelIdentityMutations([.upsert(value)]) }
        try await expectRows(store, [])
    }
    func testExistingLiveSettingsHistoryAndFavoritesSurviveMigrationAndWrites() async throws {
        let path = try url()
        let live = StoredLiveSource(name: "Fixture", sourceKind: .pasted, rawData: Data("#EXTM3U\noriginal bytes".utf8), updatedAt: date)
        let history = HistoryRecord(siteKey: "fixture", videoID: "1", title: "Original", watchedAt: date)
        let favorite = FavoriteRecord(siteKey: "fixture", videoID: "1", title: "Original", createdAt: date)
        let keys = ["live.favoriteChannels", "live.deletedChannels", "live.favoriteReferences.v1", "live.hiddenReferences.v1", "live.epg.preferences.v1", "arbitrary-setting"]
        do {
            let seed = try SQLiteStore(databaseURL: path)
            try await seed.saveLiveSource(live)
            try await seed.saveHistory(history, incognito: false)
            try await seed.saveFavorite(favorite)
            for key in keys { try await seed.setSetting(.array([.string("opaque::\(key)")]), forKey: key) }
        }
        try execute(path, "DROP TABLE \(table)")
        try execute(path, "PRAGMA user_version = 9")
        let store = try SQLiteStore(databaseURL: path)
        try await expectRows(store, []) // Schema creation never allocates identities.
        try await store.applyImportedChannelIdentityMutations([.upsert(record()), .removeAll(source: source)])
        let lives = try await store.liveSources(), histories = try await store.history(), favorites = try await store.favorites()
        XCTAssertEqual(lives, [live])
        XCTAssertEqual(histories, [history])
        XCTAssertEqual(favorites, [favorite])
        for key in keys {
            let stored = try await store.setting(forKey: key)
            XCTAssertEqual(stored, .array([.string("opaque::\(key)")]))
        }
    }
    func testPermissionsAndWALRemainConfigured() async throws {
        let store = try store()
        try await store.applyImportedChannelIdentityMutations([.upsert(record())])
        for suffix in ["", "-wal", "-shm"] {
            let attributes = try FileManager.default.attributesOfItem(atPath: fixtureURL(for: store).path + suffix)
            XCTAssertEqual((attributes[.posixPermissions] as? NSNumber)?.intValue, 0o600)
        }
        let connection = try SQLiteConnection(url: fixtureURL(for: store))
        defer { connection.close() }
        var mode: String?
        try connection.query("PRAGMA journal_mode") { mode = connection.text($0, 0) }
        XCTAssertEqual(mode, "wal")
        XCTAssertEqual(try scalar(fixtureURL(for: store), "SELECT count(*) FROM pragma_foreign_key_list('\(table)')"), 0)
    }
    func testWriterConnectionKeepsSecureDeleteAndForeignKeysEnabled() async throws {
        let store = try store()
        // The trigger executes on SQLiteStore's writer, not this fixture's
        // separate connection (these two pragmas are connection-local).
        try execute(fixtureURL(for: store), """
            CREATE TRIGGER fixture_verify_pragmas BEFORE INSERT ON \(table)
            WHEN (SELECT secure_delete FROM pragma_secure_delete) != 1
              OR (SELECT foreign_keys FROM pragma_foreign_keys) != 1
            BEGIN SELECT RAISE(ABORT, 'writer pragma changed'); END
            """)
        let expected = try record()
        try await store.applyImportedChannelIdentityMutations([.upsert(expected)])
        try await expectRows(store, [expected])
    }
    func testSourceLookupUsesIndex() async throws {
        let store = try store()
        let connection = try SQLiteConnection(url: fixtureURL(for: store))
        defer { connection.close() }
        var details: [String] = []
        try connection.query("EXPLAIN QUERY PLAN SELECT * FROM \(table) WHERE source_id = ? AND lifecycle = ?",
                             bindings: [.text("source"), .text("active")]) { details.append(connection.text($0, 3) ?? "") }
        XCTAssertTrue(details.contains {
            $0.contains("SEARCH") && ($0.contains("INDEX") || $0.contains("PRIMARY KEY"))
        }, details.joined(separator: "; "))
    }
    func testSameConnectionTransactionSupportsRegistryAndFutureMarkerAtomically() async throws {
        let store = try store(), value = try record()
        let connection = try SQLiteConnection(url: fixtureURL(for: store))
        defer { connection.close() }
        enum FixtureFailure: Error { case abort }
        XCTAssertThrowsError(try connection.transaction {
            try ImportedIdentityRegistrySQL.apply(.upsert(value), connection: connection)
            try connection.execute("INSERT INTO settings (key, value) VALUES (?, ?)",
                bindings: [.text("fixture.future-migration-marker"), .blob(Data("true".utf8))])
            throw FixtureFailure.abort
        })
        try await expectRows(store, [])
        let marker = try await store.setting(forKey: "fixture.future-migration-marker")
        XCTAssertNil(marker)
        try connection.transaction {
            try ImportedIdentityRegistrySQL.apply(.upsert(value), connection: connection)
            try connection.execute("INSERT INTO settings (key, value) VALUES (?, ?)",
                bindings: [.text("fixture.future-migration-marker"), .blob(Data("true".utf8))])
        }
        try await expectRows(store, [value])
        let committed = try await store.setting(forKey: "fixture.future-migration-marker")
        XCTAssertEqual(committed, .bool(true))
    }
    func testLargeBatchCorrectnessWithoutPerRecordTransactions() async throws {
        let store = try store(), values = try (1...1000).map { try record($0) }
        try await store.applyImportedChannelIdentityMutations(values.reversed().map(ImportedChannelRegistryMutation.upsert))
        try await expectRows(store, values)
    }
}
